import type { Metadata } from "next"; 
import { Quicksand, Montserrat } from "next/font/google";
import "../globals.css";
 

const quicksandSans = Montserrat({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/images/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="de"> 
      <body className={`${quicksandSans.className}  antialiased`} >

        <div className="flex min-h-screen flex-col items-start justify-start bg-zinc-50 font-sans dark:bg-black md:items-center md:justify-center">
          <main className="flex min-h-screen w-full max-w-full md:max-w-3xl flex-col items-center justify-between py-8 px-2 sm:px-4 md:px-16 bg-white dark:bg-black sm:items-start min-w-0 break-words">
            {/* {children} */}
            {children}
          </main>
        </div>
 
      </body>
    </html>
  );
}
