import type { Metadata } from "next"; 
import { Quicksand, Montserrat } from "next/font/google";
import "../globals.css";
 

const quicksandSans = Montserrat({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${quicksandSans.className}  antialiased`} >

        <div className="flex min-h-screen items-center justify-center bg-zinc-50 font-sans dark:bg-black">
              <main className="
                flex min-h-screen w-full max-w-3xl flex-col items-center justify-between
                py-16 px-8
                md:py-32 md:px-16
                bg-white dark:bg-black
                sm:items-start
              ">
                  {children}
              </main>
        </div>
 
      </body>
    </html>
  );
}
